version: '3'

services:
  # redis:
  #    image: 'redislabs/redismod'
  #    ports:
  #      - '6379:6379'

  api-gateway:
    build: ./api-gateway
    ports:
    - '80:80'

  frontend-admin:
    build: ./frontend-admin
    ports:
      - "8080:80"

  map-service:
    build: ./map-service
    ports:
      - "3000:3000"
    # environment:
    #  - MONGODB_URI=mongodb://map-service-db:27017/MapServiceDB

  map-service-db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: