version: '3'

services:
  api-gateway:
    build: ./api-gateway
    ports:
    - '80:80'

  frontend-admin:
    build: ./frontend-admin
    ports:
      - "8080:80"

  frontend-patient:
    build: ./frontend-patient/client
    ports:
      - "5173:80"

  frontend-dentist:
    build: ./frontend-dentist
    ports:
      - "5174:80"

  map-service:
    build: ./map-service
    ports:
      - "3000:3000"

  map-service-db:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: